const CFG={id:'2523c510-9ff0-415b-9582-93949bfae7e3',chunk:65536,dnPack:32768,dnTail:512,dnQr:4,upPack:16384,maxED:8192,concur:4};
export default{fetch:r=>r.headers.get('Upgrade')?.toLowerCase()==='websocket'?ws(r,new URL(r.url).pathname):new Response('OK')};
const hx=c=>(c>64?c+9:c)&0xF;
const idB=new Uint8Array(16),dec=new TextDecoder();
for(let i=0,p=0,c,h;i<16;i++){c=CFG.id.charCodeAt(p++);c===45&&(c=CFG.id.charCodeAt(p++));h=hx(c);c=CFG.id.charCodeAt(p++);c===45&&(c=CFG.id.charCodeAt(p++));idB[i]=h<<4|hx(c);}
const[I0,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13,I14,I15]=idB;
const mID=c=>c[1]===I0&&c[2]===I1&&c[3]===I2&&c[4]===I3&&c[5]===I4&&c[6]===I5&&c[7]===I6&&c[8]===I7&&c[9]===I8&&c[10]===I9&&c[11]===I10&&c[12]===I11&&c[13]===I12&&c[14]===I13&&c[15]===I14&&c[16]===I15;
const addr=(t,b)=>t===1?`${b[0]}.${b[1]}.${b[2]}.${b[3]}`:t===3?dec.decode(b):`[${Array.from({length:8},(_,i)=>((b[i*2]<<8)|b[i*2+1]).toString(16)).join(':')}]`;
const pAddr=(b,o,t)=>{const l=t===3?b[o++]:t===1?4:t===4?16:null;if(l===null)return null;const n=o+l;return n>b.length?null:{tAB:b.subarray(o,n),dO:n};};
const parseP=(c)=>{if(c.length<24||!mID(c))return null;let o=19+c[17];const p=(c[o]<<8)|c[o+1];let t=c[o+2];if(t!==1)t+=1;const a=pAddr(c,o+3,t);return a?{aT:t,...a,port:p}:null;};
const sprout=(f,h,p,s=f.connect({hostname:h,port:p}))=>s.opened.then(()=>s);
const raceSprout=(f,h,p)=>{if(!f?.connect)return Promise.reject(new Error('unavail'));if(CFG.concur<=1)return sprout(f,h,p);const ts=Array(CFG.concur).fill().map(()=>sprout(f,h,p));return Promise.any(ts).then(w=>{ts.forEach(t=>t.then(s=>s!==w&&s.close(),()=>{}));return w;});};
let pCfg=null,sCfg=null,eSocks=null,gCfg=null;
const pAP=seg=>{if(seg.startsWith("[")){const m=seg.match(/^\[(.+?)\]:(\d+)$/);if(m)return[m[1],Number(m[2])];return[seg.slice(1,-1),443];}const[a,port=443]=seg.split(":");return[a,Number(port)];};
const s5AP=raw=>{let u,p,ho,po;if(raw.includes('://')&&!raw.match(/^(socks5?|https?):\/\//i)){const ur=new URL(raw);ho=ur.hostname;po=ur.port||(ur.protocol==='http:'?80:1080);const au=ur.username||ur.password?`${ur.username}:${ur.password}`:ur.username;if(au&&au.includes(':'))[u,p]=au.split(':');else if(au){try{const d=atob(au.replace(/%3D/g,'=').padEnd(au.length+(4-au.length%4)%4,'='));const x=d.split(':');if(x.length===2)[u,p]=x;}catch(e){}}}else{let ap='',hp=raw;const at=raw.lastIndexOf('@');if(at!==-1){ap=raw.substring(0,at);hp=raw.substring(at+1);}if(ap&&!ap.includes(':')){try{const d=atob(ap.replace(/%3D/g,'=').padEnd(ap.length+(4-ap.length%4)%4,'='));const x=d.split(':');if(x.length===2)[u,p]=x;}catch(e){}}if(!u&&ap&&ap.includes(':'))[u,p]=ap.split(':');const[h,pp]=pAP(hp);ho=h;po=pp||(raw.includes('http=')?80:1080);}if(!ho||isNaN(po))throw new Error("bad");return{username:u,password:p,hostname:ho,port:po};};
async function s5C(f,aT,aR,pR,cfg){const{username,password,hostname,port}=cfg;const sk=f.connect({hostname,port});await sk.opened;const wr=sk.writable.getWriter();await wr.write(new Uint8Array([5,username?2:1,0,username?2:0]));const rd=sk.readable.getReader();const enc=new TextEncoder();let rs=(await rd.read()).value;if(rs[1]===2){const au=new Uint8Array([1,username.length,...enc.encode(username),password.length,...enc.encode(password)]);await wr.write(au);rs=(await rd.read()).value;if(rs[1]!==0)throw new Error("fail");}let DST;if(aT===1)DST=new Uint8Array([1,...aR.split(".").map(Number)]);else if(aT===2)DST=new Uint8Array([3,aR.length,...enc.encode(aR)]);else if(aT===3){const bs=aR.slice(1,-1).split(':').flatMap(h=>[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16)]);DST=new Uint8Array([4,...bs]);}await wr.write(new Uint8Array([5,1,0,...DST,(pR>>8)&0xff,pR&0xff]));rs=(await rd.read()).value;if(rs[1]!==0)throw new Error("fail");wr.releaseLock();rd.releaseLock();return sk;}
async function hC(f,aT,aR,pR,cfg){const{username,password,hostname,port}=cfg;const sk=f.connect({hostname,port});await sk.opened;let rq=`CONNECT ${aR}:${pR} HTTP/1.1\r\nHost: ${aR}:${pR}\r\n`;if(username&&password)rq+=`Proxy-Authorization: Basic ${btoa(`${username}:${password}`)}\r\n`;rq+=`User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36\r\nConnection: keep-alive\r\n\r\n`;const wr=sk.writable.getWriter();await wr.write(new TextEncoder().encode(rq));wr.releaseLock();const rd=sk.readable.getReader();let bf=new Uint8Array(0);while(true){const{value,done}=await rd.read();if(done)throw new Error("closed");const tm=new Uint8Array(bf.length+value.length);tm.set(bf);tm.set(value,bf.length);bf=tm;if(bf.length>65536)throw new Error("too large");const tx=new TextDecoder().decode(bf);if(tx.includes("\r\n\r\n")){if(/^HTTP\/1\.[01] 2/i.test(tx.split("\r\n")[0])){rd.releaseLock();return sk;}throw new Error(`refused: ${tx.split("\r\n")[0]}`);}}}
function pPC(path){pCfg=null;sCfg=null;eSocks=null;gCfg=null;const gm=path.match(/(socks5?|https?):\/\/([^/#?]+)/i);if(gm){const cfg=s5AP(gm[2]);gCfg={type:gm[1].toLowerCase().includes('5')||gm[1]==='socks'?'s5':'http',cfg};return;}const im=path.match(/(?:^|\/)(?:proxy)?ip[=\/](.+?)(?:\?|#|$)/i);if(im){const seg=im[1];const[addr,port]=pAP(seg);pCfg={address:addr.includes('[')?addr.slice(1,-1):addr,port:+port};}const lm=path.match(/(?:^|\/)(socks5?|s5|http)[=\/]([^/#?]+)/i);if(lm){const seg=lm[2];sCfg=s5AP(seg);eSocks=lm[1].toLowerCase().includes('http')?'http':'s5';}}
async function tC(f,host,port,aT){const st=(aT===3||aT===4)?aT-1:aT;if(gCfg){if(gCfg.type==='s5')return await s5C(f,st,host,port,gCfg.cfg);if(gCfg.type==='http')return await hC(f,st,host,port,gCfg.cfg);}try{const sk=f.connect({hostname:host,port:port});if(sk.opened)await sk.opened;return sk;}catch(err){if(!sCfg&&!pCfg)throw err;if(sCfg){try{const ls=eSocks==='http'?await hC(f,st,host,port,sCfg):await s5C(f,st,host,port,sCfg);if(ls.opened)await ls.opened;return ls;}catch(e){}}if(pCfg){try{const ps=f.connect({hostname:pCfg.address,port:pCfg.port});if(ps.opened)await ps.opened;return ps;}catch(e){}}throw err;}}
const mkK=(cap,cpy=0)=>{let q=[],h=0,b=0,buf=null;const e=()=>h>=q.length;const trim=()=>{h>32&&h*2>=q.length&&(q=q.slice(h),h=0);};const clear=()=>{q=[];h=0;b=0;};const take=()=>{if(e())return null;const d=q[h];q[h++]=undefined;b-=d.byteLength;trim();return d;};const sow=d=>{const n=d?.byteLength||0;return!n||(q.push(d),b+=n,1);};const pack=d=>{d||=take();if(!d||e())return[d,0];let n=d.byteLength,j=h;while(j<q.length){const x=q[j],nn=n+x.byteLength;if(nn>cap)break;n=nn;j++;}if(j===h)return[d,0];const out=buf||=(new Uint8Array(cap));out.set(d);for(let o=d.byteLength;h<j;){const x=q[h];q[h++]=undefined;b-=x.byteLength;out.set(x,o);o+=x.byteLength;}trim();const u=out.subarray(0,n);return[cpy?u.slice():u,1];};return{e,get b(){return b;},clear,take,sow,pack};};
const mkQ=cap=>{const k=mkK(cap);return{get empty(){return k.e();},clear:k.clear,sow:k.sow,bundle:d=>k.pack(d)};};
const mkDn=w=>{const cap=CFG.dnPack,tail=CFG.dnTail,low=Math.max(4096,tail*12),k=mkK(cap,1);let tp=0,gen=0,qk=0,qr=0;const reap=()=>{tp&&clearTimeout(tp);tp=0;qr=0;for(;;){const[u]=k.pack();if(!u)break;w.send(u);}};const ripen=()=>{if(k.e()||tp)return;if(k.b>=cap||cap-k.b<tail)return reap();tp=setTimeout(()=>{tp=0;if(k.e())return;if(k.b>=cap||cap-k.b<tail)return reap();if(qr<CFG.dnQr&&(gen!==qk||k.b<low)){qr++;qk=gen;return ripen();}reap();},1);};return{send(u){let o=0,n=u?.byteLength||0;if(!n)return;while(o<n){const m=Math.min(cap-k.b,n-o);if(!m){reap();continue;}k.sow(o||m!==n?u.subarray(o,o+m):u);gen++;o+=m;if(k.b>=cap||cap-k.b<tail)reap();else ripen();}},reap};};
const mill=async(rd,w)=>{const r=rd.getReader({mode:'byob'}),tx=mkDn(w);let buf=new ArrayBuffer(CFG.chunk);try{for(;;){const{done,value:v}=await r.read(new Uint8Array(buf,0,CFG.chunk));if(done)break;if(!v?.byteLength)continue;if(v.byteLength>=(CFG.chunk>>1))tx.reap(),w.send(v),buf=new ArrayBuffer(CFG.chunk);else tx.send(v.slice()),buf=v.buffer;}tx.reap();}catch{}finally{try{tx.reap()}catch{}try{r.releaseLock()}catch{}}}
const ws=async(req,path)=>{const[client,server]=Object.values(new WebSocketPair());server.accept({allowHalfOpen:true});server.binaryType='arraybuffer';const fetcher=req.fetcher||null;const url=new URL(req.url);const pathname=decodeURIComponent(url.pathname);pPC(pathname);const edStr=req.headers.get('sec-websocket-protocol');const ed=edStr&&edStr.length<=CFG.maxED*4/3+4?Uint8Array.fromBase64(edStr,{alphabet:'base64url'}):null;let curW=null,sock=null,closed=false,busy=false;const uq=mkQ(CFG.upPack);const wither=()=>{if(closed)return;closed=true;uq.clear();try{curW?.releaseLock()}catch{}try{sock?.close()}catch{}try{server.close()}catch{};};const toU8=d=>d instanceof Uint8Array?d:ArrayBuffer.isView(d)?new Uint8Array(d.buffer,d.byteOffset,d.byteLength):new Uint8Array(d);const sow=d=>{const u=toU8(d),n=u.byteLength;if(!n)return 1;if(uq.sow(u))return 1;wither();return 0;};const thresh=async()=>{if(busy||closed)return;busy=true;try{for(;;){if(closed)break;if(!sock){const[d]=uq.bundle();if(!d)break;const r=parseP(d);if(!r)throw wither();server.send(new Uint8Array([d[0],0]));const host=addr(r.aT,r.tAB),port=r.port,payload=d.subarray(r.dO);sock=await tC(fetcher,host,port,r.aT);if(!sock)throw wither();curW=sock.writable.getWriter();const[first]=uq.bundle(payload);first?.byteLength&&await curW.write(first);mill(sock.readable,server).finally(()=>wither());continue;}const[d]=uq.bundle();if(!d)break;await curW.write(d);}}catch{wither();}finally{busy=false;!uq.empty&&!closed&&thresh();}};if(ed&&sow(ed))thresh();server.addEventListener('message',e=>{closed||(sow(e.data)&&thresh());});server.addEventListener('close',()=>wither());server.addEventListener('error',()=>wither());return new Response(null,{status:101,webSocket:client,headers:{'Sec-WebSocket-Extensions':''}});};
